# Generated by Django 2.0.13 on 2020-06-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='tb_projects',
        ),
    ]
